In [5]:
import numpy as np

### 1. Sales Data (Retail Store Example)

Each row = a product, each column = monthly sales.

In [6]:
sales_data = np.array([
    [101, 230, 250, 270],   # Product A
    [150, 180, 200, 210],   # Product B
    [90,  120, 140, 160],   # Product C
    [300, 320, 330, 340]    # Product D
])



In [7]:
# Q.1 How many products and months are there in the dataset?
print(np.shape(sales_data))

(4, 4)


In [8]:
# Q.2 What is the total sales of all products combined?
print(np.sum(sales_data))

3391


In [9]:
# Q.3 What is the total sales for each product?
total_sales = np.sum(sales_data ,axis=1)
print(total_sales)

[ 851  740  510 1290]


In [10]:
# Q.4 What is the total sales for each month?
monthly_sales = np.sum(sales_data, axis=0)
print("monthly sales :",monthly_sales)

monthly sales : [641 850 920 980]


In [11]:
# Q.5 What is the average sales of each product?
average_sal = np.mean(sales_data ,axis=1)

print("average sales : ", average_sal.reshape((4,1)))


average sales :  [[212.75]
 [185.  ]
 [127.5 ]
 [322.5 ]]


In [15]:
# Q.6 Which month had the highest total sales?
best_month = np.argmax(np.sum(sales_data ,axis = 0))
print("best month sales index : ", best_month)


best month sales index :  3


In [ ]:
# Q.7 Which product had the highest overall sales?
highest_slaes_of_the_product = np.argmax(np.sum(sales_data, axis= 1))
print("highest sales product index : ",highest_slaes_of_the_product) 

3


In [26]:
# Q.8 What were the sales of Product B in February?
# select_feb = sales_data[: , 1]
# print("sales of Product B in February :",select_feb[1])
#  or 

print("sales of Product B in February :" ,sales_data[1,1])

sales of Product B in February : 180


In [27]:
# Q.9 What were the sales of all products in March?
print(sales_data[: , 2])

[250 200 140 330]


In [28]:
# Q.10 What were the sales of Product D across all months?

print(sales_data[3 , :])

[300 320 330 340]


In [30]:
# Q.11 What is the cumulative sales of each product month by month?
cumsum = np.cumsum(sales_data , axis=1)
print("cumulative sales of each product month by month is :\n " ,cumsum)

cumulative sales of each product month by month is :
  [[ 101  331  581  851]
 [ 150  330  530  740]
 [  90  210  350  510]
 [ 300  620  950 1290]]


In [31]:
# Q.12 Which products have total sales greater than 800?
total_sales_product = np.sum(sales_data , axis=1)
print(sales_data[total_sales_product>800])

[[101 230 250 270]
 [300 320 330 340]]


In [35]:
# Q.13 What percentage of total sales does each product contribute?
total= np.sum(sales_data)
product_total = np.sum(sales_data, axis = 1)
print("persentage of each product :\n", (product_total/total)*100)


persentage of each product :
 [25.09584193 21.82247125 15.03981127 38.04187555]


In [37]:
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10],
                [11,12,13,14,15]])*2
print(arr)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


In [ ]:
# Q.15