## numpy Array Operations

In [2]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing :", arr[1:5])
print("slicing with steps :", arr[1:7:2]) # where 2 is steps
print("negetive indexing : ", arr[-4])

Basic slicing : [2 3 4 5]
slicing with steps : [2 4 6]
negetive indexing :  6


In [13]:
arr_2d = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]] )
print("spacifice Element :" , arr_2d[1,3])   # first row , third element
print("Entire row :" , arr_2d[1])
print("Entire column :" , arr_2d[:,2])  # all rows and 2nd column

spacifice Element : 8
Entire row : [5 6 7 8]
Entire column : [ 3  7 11]


### sorting

In [17]:
unsorted = np.array([1,6,4,6,3,67,35,34,785,34])
print("sorted array : ", np.sort(unsorted))

arr_2d_unsorted = np.array([[1,3],[2,1],[3,2]])
print("Sorted 2D array by column wise :\n ", np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D array by row wise :\n ", np.sort(arr_2d_unsorted,axis=1))

sorted array :  [  1   3   4   6   6  34  34  35  67 785]
Sorted 2D array by column wise :
  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row wise :
  [[1 3]
 [1 2]
 [2 3]]


## filter 

In [6]:
numbers =np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers %2==0]
print("Even numbers : ", even_number)

Even numbers :  [ 2  4  6  8 10]


## filter with mask

In [ ]:
mask = numbers>5
print("numbers is grater then 5 : " , numbers[mask])

numbers is grater then 5 :  [ 6  7  8  9 10]


### fancy indexing vs np.where()

In [10]:
indices = [1,3,4]
print(numbers[indices])

where_result = np.where(numbers>5) # its returing indices
print(where_result)
print("NP where :", numbers[where_result])

[2 4 5]
(array([5, 6, 7, 8, 9]),)
NP where : [ 6  7  8  9 10]


In [13]:
condition_array= np.where(numbers > 5 , numbers*3 ,numbers)
print(condition_array)

[ 1  2  3  4  5 18 21 24 27 30]


### concadinate arrays

In [23]:
# 1d array
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
combined = np.concatenate((arr1 ,arr2))
print(combined)

# 2d arrays 
arr_2d_1 = np.array([[1,2,3],
                     [4,5,6]])
arr_2d_2 = np.array([[7,8,9]])
combined_2d_col_wise = np.concatenate((arr_2d_1, arr_2d_2),axis=0)
print(combined_2d_col_wise)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### one or method to adding new rows and column

In [25]:
original_arr = np.array([[1,2],
                         [3,4]])
new_arr = np.array([[5,6]])
# add for row wise
with_new_arr = np.vstack((original_arr,new_arr))
print(with_new_arr)

# add for column wise
arr = np.array([[1,2],
              [3,4]]) 
new_arr = np.array([[8],[9]])
add_col_wise= np.hstack((arr, new_arr))
print(add_col_wise)


[[1 2]
 [3 4]
 [5 6]]
[[1 2 8]
 [3 4 9]]


### array compatiblity

In [21]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c= np.array([7,8,9,10])

print("compatiblity shapes :" , a.shape == b.shape)
print("compatiblity shapes :" , b.shape == c.shape)

compatiblity shapes : True
compatiblity shapes : False


### deletion

In [ ]:
arr = np.array([1,2,3,4,5,6])
deletion= np.delete(arr,2)
print("array after deletion :", deletion)
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
deletion_2d= np.delete(arr_2d,1, axis=0)
print("array after deletion :\n", deletion_2d)
deletion_2d_col= np.delete(arr_2d,1, axis=1) # where 1 is index those we went to delete
print("array after deletion :\n", deletion_2d_col)



array after deletion : [1 2 4 5 6]
array after deletion :
 [[1 2 3]
 [7 8 9]]
array after deletion :
 [[1 3]
 [4 6]
 [7 9]]
