## numpy array and basics
learn about numpy

In [3]:
import numpy as np

### creating array form list 

In [6]:
arr_1d = np.array([1,2,3,4])
print("1D array :", arr_1d)

arr_2d = np.array([[1,2,3],[ 4,5,6]])
print("2D array :", arr_2d)

1D array : [1 2 3 4]
2D array : [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [25]:
py_list = [1,2,3,4]
print("python list multiplication : ", py_list *2)

np_array= np.array([1,2,3,4]) # element wise multiplication 
print("numpy array multiplication : ", np_array *2)

import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time  : ", time.time()- start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n numpy operation time  : ", time.time()- start)


python list multiplication :  [1, 2, 3, 4, 1, 2, 3, 4]
numpy array multiplication :  [2 4 6 8]

 List operation time  :  0.16031146049499512

 numpy operation time  :  0.010495901107788086


### creating array from scratch

In [ ]:
zeros = np.zeros((5,7))# 5 rows and 7 col
print("Zeros : \n" , zeros)

ones = np.ones((3,4))
print("ones array : \n" , ones)

# constant array 
full = np.full((4,4),7) # 4x4 matrix and constant value is 7
print("full array : \n" , full)

# random values in array 

random = np.random.random((3,4))
print("random array : \n" , random)

sequence = np.arange(0,11, 2) # where 2 is steps
print("sequence array : \n" , sequence)

Zeros : 
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array : 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array : 
 [[0.56286686 0.84091344 0.84333928 0.16359433]
 [0.14475932 0.59040144 0.52093201 0.99079253]
 [0.27135046 0.68033026 0.1063178  0.90990972]]
sequence array : 
 [ 0  2  4  6  8 10]


### vector , matrix and tensor

In [44]:
vector = np.array([1,2,3,4,5])
print("Vector : " , vector)

matrix = np.array([[1,2,3],
                   [5,6,7]])
print("matrix :\n " , matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6],[7,8]]])
print("Tensor : \n" , tensor)

Vector :  [1 2 3 4 5]
matrix :
  [[1 2 3]
 [5 6 7]]
Tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array properties

In [50]:
arr = np.array([[1,2],
                [3,4]])
print("Shape : " , arr.shape)  # gives rows and colmn
print("size : " , arr.size)  # gives number of element 
print("Dimantions : " , arr.ndim)  # gives dimantion 
print("data type : " , arr.dtype)  # gives data types
print("data type : " , arr)  # gives data types

Shape :  (2, 2)
size :  4
Dimantions :  2
data type :  int64
data type :  [[1 2]
 [3 4]]


### Array Reshaping

In [60]:
arr = np.arange(12)
print("Orignal array : ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array : \n " , reshaped)

flattened = reshaped.flatten()  # its return copy array
print("flattened array : \n " , flattened)

raveled = reshaped.ravel()  # its return original array
print("reveled array : \n " , raveled)

# Transposes 
transpose = reshaped.T
print("transpose array : \n " , transpose)




Orignal array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : 
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array : 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled array : 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array : 
  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
